version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: todo_app-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_app_network

  app:
    build: .
    container_name: todo_app-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - todo_app_network

  db:
    image: mysql:5.6
    container_name: todo_app-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pwd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=todo_app
    ports:
      - "3306:3306"
    volumes:
      - todo_app_db_volume:/var/lib/mysql
    networks:
      - todo_app_network

networks:
  todo_app_network:
    driver: bridge

volumes:
  todo_app_db_volume: